WEAPON_NAMES_BY_ID = {
    'AEK-971': {'type': 'assault rifle', 'name': 'AEK-971'},
    'Weapons/AK74M/AK74': {'type': 'assault rifle', 'name': 'AK-74M', 'kit': 'assault'},
    'AN-94 Abakan': {'type': 'assault rifle', 'name': 'AN-94', 'kit': 'assault'},
    'Steyr AUG': {'type': 'assault rifle', 'name': 'AUG A3', 'kit': 'assault'},
    'F2000': {'type': 'assault rifle', 'name': 'F2000', 'kit': 'assault'},
    'FAMAS': {'type': 'assault rifle', 'name': 'FAMAS', 'kit': 'assault'},
    'Weapons/G3A3/G3A3': {'type': 'assault rifle', 'name': 'G3A3', 'kit': 'assault'},
    'Weapons/KH2002/KH2002': {'type': 'assault rifle', 'name': 'KH2002', 'kit': 'assault'},
    'Weapons/XP1_L85A2/L85A2': {'type': 'assault rifle', 'name': 'L85A2', 'kit': 'assault'},
    'M16A4': {'type': 'assault rifle', 'name': 'M16A3', 'kit': 'assault'},
    'M416': {'type': 'assault rifle', 'name': 'M416', 'kit': 'assault'},
    'SCAR-L': {'type': 'assault rifle', 'name': 'SCAR-L', 'kit': 'assault'},
    'Defib': {'type': None, 'name': 'DEFIBRILLATOR', 'kit': 'assault'},
    'M320': {'type': None, 'name': 'M320', 'kit': 'assault'},
    'M26Mass': {'type': 'shotgun', 'name': 'M26 MASS', 'kit': 'assault'},

    # engineer
    'Weapons/A91/A91': {'type': 'carbines', 'name': 'A-91', 'kit': 'engineer'},
    'Weapons/XP2_ACR/ACR': {'type': 'carbines', 'name': 'ACW-R', 'kit': 'engineer'},
    'AKS-74u': {'type': 'carbines', 'name': 'AKS-74', 'kit': 'engineer'},
    'Weapons/G36C/G36C': {'type': 'carbines', 'name': 'G36C', 'kit': 'engineer'},
    'HK53': {'type': 'carbines', 'name': 'G53', 'kit': 'engineer'},
    'M4A1': {'type': 'carbines', 'name': 'M4A1', 'kit': 'engineer'},
    'Weapons/XP2_MTAR/MTAR': {'type': 'carbines', 'name': 'MTAR-21', 'kit': 'engineer'},
    'QBZ-95': {'type': 'carbines', 'name': 'QBZ-95B', 'kit': 'engineer'},
    'Weapons/SCAR-H/SCAR-H': {'type': 'carbines', 'name': 'SCAR-H', 'kit': 'engineer'},
    'SG 553 LB': {'type': 'carbines', 'name': 'SG553', 'kit': 'engineer'},

    'FIM92': {'type': 'launcher', 'name': 'FIM-92 STINGER', 'kit': 'engineer'},
    'Weapons/Sa18IGLA/Sa18IGLA': {'type': 'launcher', 'name': 'SA-18 IGLA', 'kit': 'engineer'},
    'FGM-148': {'type': 'launcher', 'name': 'FGM-148 JAVELIN', 'kit': 'engineer'},
    'RPG-7': {'type': 'launcher', 'name': 'RPG-7V2', 'kit': 'engineer'},
    'SMAW': {'type': 'launcher', 'name': 'SMAW', 'kit': 'engineer'},

    'Repair Tool': {'type': '', 'name': 'REPAIR TOOL', 'kit': 'engineer'},
    'M15 AT Mine': {'type': 'explosive', 'name': 'M15 AT MINE', 'kit': 'engineer'},
    'EOD BOT': {'type': '', 'name': 'EOD BOT', 'kit': 'engineer'},

    # supporter
    'Weapons/XP2_L86/L86': {'type': 'LMG', 'name': 'L86A2', 'kit': 'support'},
    'LSAT': {'type': 'LMG', 'name': 'LSAT', 'kit': 'support'},
    'M240': {'type': 'LMG', 'name': 'M240B', 'kit': 'support'},
    'M249': {'type': 'LMG', 'name': 'M249', 'kit': 'support'},
    'M27IAR': {'type': 'LMG', 'name': 'M27 IAR', 'kit': 'support'},
    'M60': {'type': 'LMG', 'name': 'M60E4', 'kit': 'support'},
    'MG36': {'type': 'LMG', 'name': 'MG36', 'kit': 'support'},
    'Pecheneg': {'type': 'LMG', 'name': 'PKP PECHENEG', 'kit': 'support'},
    'QBB-95': {'type': 'LMG', 'name': 'QBB-95', 'kit': 'support'},
    'RPK-74M': {'type': 'LMG', 'name': 'RPK-74M', 'kit': 'support'},
    'Type88': {'type': 'LMG', 'name': 'TYPE 88 LMG', 'kit': 'support'},

    'Weapons/Gadgets/C4/C4': {'type': 'explosive', 'name': 'C4 EXPLOSIVES', 'kit': 'support'},
    'Weapons/Gadgets/Claymore/Claymore': {'type': 'explosive', 'name': 'M18 CLAYMORE', 'kit': 'support'},

    # sniper
    'M417': {'type': 'sniper rifle', 'name': 'M417', 'kit': 'recon'},
    'JNG90': {'type': 'sniper rifle', 'name': 'JNG-90', 'kit': 'recon'},
    'L96': {'type': 'sniper rifle', 'name': 'L96', 'kit': 'recon'},
    'M39': {'type': 'sniper rifle', 'name': 'M39 EMR', 'kit': 'recon'},
    'M40A5': {'type': 'sniper rifle', 'name': 'M40A5', 'kit': 'recon'},
    'Model98B': {'type': 'sniper rifle', 'name': 'M98B', 'kit': 'recon'},
    'Mk11': {'type': 'sniper rifle', 'name': 'MK11 MOD 0', 'kit': 'recon'},
    'QBU-88': {'type': 'sniper rifle', 'name': 'QBU-88', 'kit': 'recon'},
    'SKS': {'type': 'sniper rifle', 'name': 'SKS', 'kit': 'recon'},
    'SV98': {'type': 'sniper rifle', 'name': 'SV98', 'kit': 'recon'},
    'SVD': {'type': 'sniper rifle', 'name': 'SVD', 'kit': 'recon'},
    'MAV': {'type': None, 'name': 'MAV', 'kit': 'recon'},

    # general
    '870MCS': {'type': 'shotgun', 'name': '870MCS', 'kit': 'general'},
    'DAO-12': {'type': 'shotgun', 'name': 'DAO-12', 'kit': 'general'},
    'jackhammer': {'type': 'shotgun', 'name': 'MK3A1', 'kit': 'general'},
    'M1014': {'type': 'shotgun', 'name': 'M1014', 'kit': 'general'},
    'SPAS-12': {'type': 'shotgun', 'name': 'SPAS-12', 'kit': 'general'},
    'Siaga20k': {'type': 'shotgun', 'name': 'SAIGA 12K', 'kit': 'general'},
    'USAS-12': {'type': 'shotgun', 'name': 'USAS-12', 'kit': 'general'},


    # general smg
    'Weapons/XP2_MP5K/MP5K': {'type': 'smg', 'name': 'M5K', 'kit': 'general'},
    'MP7': {'type': 'smg', 'name': 'MP7', 'kit': 'general'},
    'Weapons/P90/P90': {'type': 'smg', 'name': 'P90', 'kit': 'general'},
    'Weapons/MagpulPDR/MagpulPDR': {'type': 'smg', 'name': 'PDW-R', 'kit': 'general'},
    'PP-19': {'type': 'smg', 'name': 'PP-19', 'kit': 'general'},
    'PP-2000': {'type': 'smg', 'name': 'PP-2000', 'kit': 'general'},
    'Weapons/UMP45/UMP45': {'type': 'smg', 'name': 'UMP-45', 'kit': 'general'},
    'AS Val': {'type': 'smg', 'name': 'AS VAL', 'kit': 'general'},

    'M67': {'type': None, 'name': 'M67 GRENADE', 'kit': 'general'},
    # knifekill with animation
    'Knife_RazorBlade': {'type': 'all', 'name': 'ACB-90', 'kit': 'general'},
    # knifekill normal
    'Melee': {'type': 'all', 'name': 'ACB-90', 'kit': 'general'},
    'Weapons/Knife/Knife': {'type': 'all', 'name': 'ACB-90', 'kit': 'general'},
    'CrossBow': {'type': 'handgun', 'name': 'XBOW', 'kit': 'general'},

    # Pistols
    'M1911': {'type': 'handgun', 'name': 'M1911', 'kit': 'general'},
    'Weapons/MP412Rex/MP412REX': {'type': 'handgun', 'name': 'MP412 REX', 'kit': 'general'},
    'M9': {'type': 'handgun', 'name': 'M9', 'kit': 'general'},
    'M93R': {'type': 'handgun', 'name': '93R', 'kit': 'general'},
    'Weapons/MP443/MP443': {'type': 'handgun', 'name': 'MP443', 'kit': 'general'},
    'MP443SUPP': {'type': 'handgun', 'name': 'MP443 SUPP.', 'kit': 'general'},
    'Taurus .44': {'type': 'handgun', 'name': '.44 MAGNUM', 'kit': 'general'},
    'Glock18': {'type': 'handgun', 'name': 'G18', 'kit': 'general'},

    # others
    'Death': {'type': '', 'name': 'Death', 'kit': ''},
    'SoldierCollision': {'type': '', 'name': 'SoldierCollision', 'kit': ''},
    'RoadKill': {'type': '', 'name': 'RoadKill', 'kit': ''},
    'DamageArea': {'type': '', 'name': 'DamageArea', 'kit': ''},
    'Suicide': {'type': '', 'name': 'Suicide', 'kit': ''},

    # gunmaster weapons
    'Weapons/MP443/MP443_GM': {'type': 'handgun', 'name': 'MP443 (Gunmster mode)', 'kit': 'general'},
    'Weapons/P90/P90_GM': {'type': 'smg', 'name': 'P90 (Gunmaster Mode)', 'kit': 'general'},
}

WEAPONS_GROUPS = {
    'shotguns': ('870MCS', 'DAO-12', 'jackhammer', 'M1014', 'SPAS-12', 'Siaga20k', 'USAS-12', 'M26Mass'),
    'explosives': ('Weapons/Gadgets/Claymore/Claymore', 'M15 AT Mine', 'Weapons/Gadgets/C4/C4'),
}

BF4_WEAPON_NAMES_BY_ID = {
    # Assault Rifles
    'U_AEK971': {'type': 'assault rifle', 'name': 'AEK-971', 'kit': 'assault'},
    'U_AK12': {'type': 'assault rifle', 'name': 'AK-12', 'kit': 'assault'},
    'U_CZ805': {'type': 'assault rifle', 'name': 'CZ-805', 'kit': 'assault'},
    'U_FAMAS': {'type': 'assault rifle', 'name': 'FAMAS', 'kit': 'assault'},
    'U_GalilACE23': {'type': 'assault rifle', 'name': 'ACE-23', 'kit': 'assault'},
    'U_M16A4': {'type': 'assault rifle', 'name': 'M16A4', 'kit': 'assault'},
    'U_M416': {'type': 'assault rifle', 'name': 'M416', 'kit': 'assault'},
    'U_QBZ951': {'type': 'assault rifle', 'name': 'QBZ-95-1', 'kit': 'assault'},
    'U_SAR21': {'type': 'assault rifle', 'name': 'SAR-21', 'kit': 'assault'},
    'U_SCAR-H': {'type': 'assault rifle', 'name': 'SCAR-H', 'kit': 'assault'},
    'U_SteyrAug': {'type': 'assault rifle', 'name': 'AUG-A3', 'kit': 'assault'},
    'U_L85a2': {'type': 'assault rifle', 'name': 'L85A2', 'kit': 'assault'},

    # Carbines
    'U_A91': {'type': 'carbines', 'name': 'A-91', 'kit': 'general'},
    'U_ACR': {'type': 'carbines', 'name': 'ACW-R', 'kit': 'general'},
    'U_AK5C': {'type': 'carbines', 'name': 'AK-5C', 'kit': 'general'},
    'U_AKU12': {'type': 'carbines', 'name': 'AKU-12', 'kit': 'general'},
    'U_G36C': {'type': 'carbines', 'name': 'G36C', 'kit': 'general'},
    'U_GalilACE': {'type': 'carbines', 'name': 'ACE-21-CQB', 'kit': 'general'},
    'U_GalilACE52': {'type': 'carbines', 'name': 'ACE-52-CQB', 'kit': 'general'},
    'U_M4A1': {'type': 'carbines', 'name': 'M4', 'kit': 'general'},
    'U_SG553LB': {'type': 'carbines', 'name': 'SG553', 'kit': 'general'},
    'U_Type95B': {'type': 'carbines', 'name': 'Type-95B-1', 'kit': 'general'},
    'U_MTAR21': {'type': 'carbines', 'name': 'MTAR-21', 'kit': 'general'},

    # Designated Marksman Rifles (DMR)
    'U_GalilACE53': {'type': 'DMR', 'name': 'ACE-53-SV', 'kit': 'general'},
    'U_M39EBR': {'type': 'DMR', 'name': 'M39-EMR', 'kit': 'general'},
    'U_MK11': {'type': 'DMR', 'name': 'MK11-MOD-0', 'kit': 'general'},
    'U_QBU88': {'type': 'DMR', 'name': 'QBU-88', 'kit': 'general'},
    'U_RFB': {'type': 'DMR', 'name': 'RFB', 'kit': 'general'},
    'U_SCAR-HSV': {'type': 'DMR', 'name': 'SCAR-H-SV', 'kit': 'general'},
    'U_SKS': {'type': 'DMR', 'name': 'SKS', 'kit': 'general'},
    'U_SVD12': {'type': 'DMR', 'name': 'SVD-12', 'kit': 'general'},

    # Explosive Gadgets
    'U_C4': {'type': 'explosive', 'name': 'C4-Explosive', 'kit': 'recon'},
    'U_C4_Support': {'type': 'explosive', 'name': 'C4-Explosive', 'kit': 'support'},
    'U_Claymore': {'type': 'explosive', 'name': 'M18-Claymore', 'kit': ''},
    'U_Claymore_Recon': {'type': 'explosive', 'name': 'M18-Claymore', 'kit': 'recon'},
    'U_M15': {'type': 'explosive', 'name': 'M15-AT-Mine', 'kit': ''},
    'U_SLAM': {'type': 'explosive', 'name': 'M2-Slam', 'kit': ''},
    'U_MGL': {'type': 'explosive', 'name': 'M32-MGL', 'kit': ''},
    #'Death': {'type': 'explosive', 'name': 'M224-Mortar', 'kit': ''},
    'U_XM25': {'type': 'explosive', 'name': 'XM25-Airburst', 'kit': ''},
    'U_XM25_Flechette': {'type': 'explosive', 'name': 'XM25-Dart', 'kit': ''},
    'U_XM25_Smoke': {'type': 'explosive', 'name': 'XM25-Smoke', 'kit': ''},
    'U_UCAV': {'type': 'explosive', 'name': 'UCAV', 'kit': ''},

    # Hand Grenades
    #'': {'type': 'grenade', 'name': 'hand-flare', 'kit': 'general'},
    'U_Flashbang': {'type': 'grenade', 'name': 'M84-Flashbang', 'kit': 'general'},
    'U_Grenade_RGO': {'type': 'grenade', 'name': 'RGO-Impact', 'kit': 'general'},
    #'': {'type': 'grenade', 'name': 'M18-Smoke', 'kit': 'general'},
    'U_M34': {'type': 'grenade', 'name': 'M34-Incendiary', 'kit': 'general'},
    'U_M67': {'type': 'grenade', 'name': 'M67-Frag', 'kit': 'general'},
    'U_V40': {'type': 'grenade', 'name': 'V40-Mini', 'kit': 'general'},

    # Hand Guns
    'U_M93R': {'type': 'handgun', 'name': '93R', 'kit': 'general'},
    'U_CZ75': {'type': 'handgun', 'name': 'CZ-75', 'kit': 'general'},
    'U_FN57': {'type': 'handgun', 'name': 'FN57', 'kit': 'general'},
    'U_Glock18': {'type': 'handgun', 'name': 'G18', 'kit': 'general'},
    'U_HK45C': {'type': 'handgun', 'name': 'Compact-45', 'kit': 'general'},
    'U_M1911': {'type': 'handgun', 'name': 'M1911', 'kit': 'general'},
    'U_MP412Rex': {'type': 'handgun', 'name': 'M412-Rex', 'kit': 'general'},
    'U_M9': {'type': 'handgun', 'name': 'M9', 'kit': 'general'},
    'U_MP443': {'type': 'handgun', 'name': 'MP443', 'kit': 'general'},
    'U_P226': {'type': 'handgun', 'name': 'P226', 'kit': 'general'},
    'U_QSZ92': {'type': 'handgun', 'name': 'QSZ-92', 'kit': 'general'},
    'U_Taurus44': {'type': 'handgun', 'name': '44-Magnum', 'kit': 'general'},

    # Light Machine Guns (LMG)
    'U_LSAT': {'type': 'LMG', 'name': 'LSAT', 'kit': 'support'},
    'U_M240': {'type': 'LMG', 'name': 'M240B', 'kit': 'support'},
    'U_M249': {'type': 'LMG', 'name': 'M249', 'kit': 'support'},
    'U_MG4': {'type': 'LMG', 'name': 'MG4', 'kit': 'support'},
    'U_Pecheneg': {'type': 'LMG', 'name': 'PKP-Pecheneg', 'kit': 'support'},
    'U_QBB95': {'type': 'LMG', 'name': 'QBB-95-1', 'kit': 'support'},
    'U_RPK12': {'type': 'LMG', 'name': 'RPK-12', 'kit': 'support'},
    'U_Type88': {'type': 'LMG', 'name': 'Type-88-LMG', 'kit': 'support'},
    'U_Ultimax': {'type': 'LMG', 'name': 'U-100-MK5', 'kit': 'support'},
    'U_rpk-74': {'type': 'LMG', 'name': 'RPK-74M', 'kit': 'support'},

    # Personal Defense Weapons (PDW)
    'U_CBJ-MS': {'type': 'PWD', 'name': 'CBJ-MS', 'kit': 'general'},
    'U_JS2': {'type': 'PWD', 'name': 'JS2', 'kit': 'general'},
    'U_MX4': {'type': 'PWD', 'name': 'MX4', 'kit': 'general'},
    'U_P90': {'type': 'PWD', 'name': 'P90', 'kit': 'general'},
    'U_MagpulPDR': {'type': 'PWD', 'name': 'PDW-R', 'kit': 'general'},
    'U_PP2000': {'type': 'PWD', 'name': 'PP-2000', 'kit': 'general'},
    'U_Scorpion': {'type': 'PWD', 'name': 'CZ-3A1', 'kit': 'general'},
    'U_UMP45': {'type': 'PWD', 'name': 'UMP-45', 'kit': 'general'},
    'U_UMP9': {'type': 'PWD', 'name': 'UMP-9', 'kit': 'general'},
    'U_mp7': {'type': 'PWD', 'name': 'MP7', 'kit': 'general'},

    # Rocket Launcher
    'U_FGM148': {'type': 'explosive', 'name': 'FGM-148-Javelin', 'kit': 'engineer'},
    'U_FIM92': {'type': 'explosive', 'name': 'FIM-92-Stinger', 'kit': 'engineer'},
    'U_Sa18IGLA': {'type': 'explosive', 'name': 'SA-18-Igla', 'kit': 'engineer'},
    'U_AT4': {'type': 'explosive', 'name': 'M136-CS', 'kit': 'engineer'},
    'U_NLAW': {'type': 'explosive', 'name': 'MBT-LAW', 'kit': 'engineer'},
    'U_RPG7': {'type': 'explosive', 'name': 'RGP-7V2', 'kit': 'engineer'},
    'U_SMAW': {'type': 'explosive', 'name': 'MK153-SMAW', 'kit': 'engineer'},
    'U_SRAW': {'type': 'explosive', 'name': 'FGM-172-SRAW', 'kit': 'engineer'},
    'U_Starstreak': {'type': 'explosive', 'name': 'HVM-II', 'kit': 'engineer'},

    # Shotguns
    'U_M26Mass_Flechette': {'type': 'shotgun', 'name': 'M26-Dart', 'kit': 'general'},
    'U_M26Mass_Frag': {'type': 'shotgun', 'name': 'M26-Frag', 'kit': 'general'},
    'U_M26Mass': {'type': 'shotgun', 'name': 'M26-Mass', 'kit': 'general'},
    'U_M26Mass_Slug': {'type': 'shotgun', 'name': 'M26-Slug', 'kit': 'general'},
    'U_USAS-12_Nightvision': {'type': 'shotgun', 'name': 'USAS-12-Flir', 'kit': 'general'},
    'U_870': {'type': 'shotgun', 'name': '870-MCS', 'kit': 'general'},
    'U_DBV12': {'type': 'shotgun', 'name': 'DBV-12', 'kit': 'general'},
    'U_HAWK': {'type': 'shotgun', 'name': 'HAWK-12G', 'kit': 'general'},
    'U_M1014': {'type': 'shotgun', 'name': 'M1014', 'kit': 'general'},
    'U_QBS09': {'type': 'shotgun', 'name': 'QBS-09', 'kit': 'general'},
    'U_SAIGA_20K': {'type': 'shotgun', 'name': 'Saiga-12K', 'kit': 'general'},
    'U_SerbuShorty': {'type': 'shotgun', 'name': 'Shorty-12G', 'kit': 'general'},
    'U_SPAS12': {'type': 'shotgun', 'name': 'Spas-12', 'kit': 'general'},
    'U_USAS-12': {'type': 'shotgun', 'name': 'USAS-12', 'kit': 'general'},
    'U_UTAS': {'type': 'shotgun', 'name': 'UTS-15', 'kit': 'general'},

    # Sniper Rifle
    'U_AMR2': {'type': 'sniper', 'name': 'AMR-2', 'kit': 'recon'},
    'U_AMR2_CQB': {'type': 'sniper', 'name': 'AMR-2-CQB', 'kit': 'recon'},
    'U_AMR2_MED': {'type': 'sniper', 'name': 'AMR-2-MID', 'kit': 'recon'},
    'U_CS-LR4': {'type': 'sniper', 'name': 'CS-LR4', 'kit': 'recon'},
    'U_FY-JS': {'type': 'sniper', 'name': 'FY-JS', 'kit': 'recon'},
    'U_JNG90': {'type': 'sniper', 'name': 'JNG-90', 'kit': 'recon'},
    'U_M200': {'type': 'sniper', 'name': 'SRR-61', 'kit': 'recon'},
    'U_M40A5': {'type': 'sniper', 'name': 'M40A5', 'kit': 'recon'},
    'U_M82A3': {'type': 'sniper', 'name': 'M82A3', 'kit': 'recon'},
    'U_M82A3_CQB': {'type': 'sniper', 'name': 'M82A3-CQB', 'kit': 'recon'},
    'U_M82A3_MED': {'type': 'sniper', 'name': 'M82A3-MID', 'kit': 'recon'},
    'U_M98B': {'type': 'sniper', 'name': 'M98B', 'kit': 'recon'},
    'U_Scout': {'type': 'sniper', 'name': 'Scout-Elite', 'kit': 'recon'},
    'U_SRS': {'type': 'sniper', 'name': '338-Recon', 'kit': 'recon'},
    'U_SV98': {'type': 'sniper', 'name': 'SV-98', 'kit': 'recon'},
    'U_L96A1': {'type': 'sniper', 'name': 'L96A1', 'kit': 'recon'},

    # Knife
    'Melee': {'type': None, 'name': 'Melee', 'kit': 'general'},

    # Underslug Launcher
    'U_M320_HE': {'type': 'explosive', 'name': 'M320-HE', 'kit': 'general'},
    'U_M320_FLASH': {'type': 'explosive', 'name': 'M320-FB', 'kit': 'general'},
    'U_M320_LVG': {'type': 'explosive', 'name': 'M320-LVG', 'kit': 'general'},
    'U_M320_SHG': {'type': 'explosive', 'name': 'M320-Dart', 'kit': 'general'},
    'U_M320_SMK': {'type': 'explosive', 'name': 'M320-SMK', 'kit': 'general'},

    # Assault Rifle Underslung Launchers
    'U_AEK971_M320_HE': {'type': 'explosive', 'name': 'AEK971 M320 HE', 'kit': 'assault'},
    'U_AEK971_M320_FLASH': {'type': None, 'name': 'AEK971 M320 Flashbang', 'kit': 'assault'},
    'U_AEK971_M320_LVG': {'type': 'explosive', 'name': 'AEK971 M320 LVG', 'kit': 'assault'},
    'U_AEK971_M320_SHG': {'type': 'shotgun', 'name': 'AEK971 M320 Shotgun', 'kit': 'assault'},
    'U_AEK971_M320_SMK': {'type': None, 'name': 'AEK971 M320 Smoke', 'kit': 'assault'},
    'U_AK12_M320_HE': {'type': 'explosive', 'name': 'AK12 M320 HE', 'kit': 'assault'},
    'U_AK12_M320_FLASH': {'type': None, 'name': 'AK12 M320 Flashbang', 'kit': 'assault'},
    'U_AK12_M320_LVG': {'type': 'explosive', 'name': 'AK12 M320 LVG', 'kit': 'assault'},
    'U_AK12_M320_SHG': {'type': 'shotgun', 'name': 'AK12 M320 Shotgun', 'kit': 'assault'},
    'U_AK12_M320_SMK': {'type': None, 'name': 'AK12 M320 Smoke', 'kit': 'assault'},
    'U_CZ805_M320_HE': {'type': 'explosive', 'name': 'CZ805 M320 HE', 'kit': 'assault'},
    'U_CZ805_M320_FLASH': {'type': None, 'name': 'CZ805 M320 Flashbang', 'kit': 'assault'},
    'U_CZ805_M320_LVG': {'type': 'explosive', 'name': 'CZ805 M320 LVG', 'kit': 'assault'},
    'U_CZ805_M320_SHG': {'type': 'shotgun', 'name': 'CZ805 M320 Shotgun', 'kit': 'assault'},
    'U_CZ805_M320_SMK': {'type': None, 'name': 'CZ805 M320 Smoke', 'kit': 'assault'},
    'U_M16A4_M320_HE': {'type': 'explosive', 'name': 'M16A4 M320 HE', 'kit': 'assault'},
    'U_M16A4_M320_FLASH': {'type': None, 'name': 'M16A4 M320 Flashbang', 'kit': 'assault'},
    'U_M16A4_M320_LVG': {'type': 'explosive', 'name': 'M16A4 M320 LVG', 'kit': 'assault'},
    'U_M416_M320_SHG': {'type': 'shotgun', 'name': 'M416 M320 Shotgun', 'kit': 'assault'},
    'U_M416_M320_SMK': {'type': None, 'name': 'M416 M320 Smoke', 'kit': 'assault'},
    'U_QBZ951_M320_HE': {'type': 'explosive', 'name': 'QBZ951 M320 HE', 'kit': 'assault'},
    'U_QBZ951_M320_FLASH': {'type': None, 'name': 'QBZ951 M320 Flashbang', 'kit': 'assault'},
    'U_QBZ951_M320_LVG': {'type': 'explosive', 'name': 'QBZ951 M320 LVG', 'kit': 'assault'},
    'U_QBZ951_M320_SHG': {'type': 'shotgun', 'name': 'QBZ951 M320 Shotgun', 'kit': 'assault'},
    'U_QBZ951_M320_SMK': {'type': None, 'name': 'QBZ951 M320 Smoke', 'kit': 'assault'},
    'U_SAR21_M320_HE': {'type': 'explosive', 'name': 'SAR21 M320 HE', 'kit': 'assault'},
    'U_SAR21_M320_FLASH': {'type': None, 'name': 'SAR21 M320 Flashbang', 'kit': 'assault'},
    'U_SAR21_M320_LVG': {'type': 'explosive', 'name': 'SAR21 M320 LVG', 'kit': 'assault'},
    'U_SAR21_M320_SHG': {'type': 'shotgun', 'name': 'SAR21 M320 Shotgun', 'kit': 'assault'},
    'U_SAR21_M320_SMK': {'type': None, 'name': 'SAR21 M320 Smoke', 'kit': 'assault'},
    'U_SCAR-H_M320_HE': {'type': 'explosive', 'name': 'SCAR-H M320 HE', 'kit': 'assault'},
    'U_SCAR-H_M320_FLASH': {'type': None, 'name': 'SCAR-H M320 Flashbang', 'kit': 'assault'},
    'U_SCAR-H_M320_LVG': {'type': 'explosive', 'name': 'SCAR-H M320 LVG', 'kit': 'assault'},
    'U_SCAR-H_M320_SHG': {'type': 'shotgun', 'name': 'SCAR-H M320 Shotgun', 'kit': 'assault'},
    'U_SCAR-H_M320_SMK': {'type': None, 'name': 'SCAR-H M320 Smoke', 'kit': 'assault'},
    'U_SteyrAug_M320_HE': {'type': 'explosive', 'name': 'SteyrAug M320 HE', 'kit': 'assault'},
    'U_SteyrAug_M320_FLASH': {'type': None, 'name': 'SteyrAug M320 Flashbang', 'kit': 'assault'},
    'U_SteyrAug_M320_LVG': {'type': 'explosive', 'name': 'SteyrAug M320 LVG', 'kit': 'assault'},
    'U_SteyrAug_M320_SHG': {'type': 'shotgun', 'name': 'SteyrAug M320 Shotgun', 'kit': 'assault'},
    'U_SteyrAug_M320_SMK': {'type': None, 'name': 'SteyrAug M320 Smoke', 'kit': 'assault'},
    'U_L85a2_M320_HE': {'type': 'explosive', 'name': 'L85a2 M320 HE', 'kit': 'assault'},
    'U_L85a2_M320_FLASH': {'type': None, 'name': 'L85a2 M320 Flashbang', 'kit': 'assault'},
    'U_L85a2_M320_LVG': {'type': 'explosive', 'name': 'L85a2 M320 LVG', 'kit': 'assault'},
    'U_L85a2_M320_SHG': {'type': 'shotgun', 'name': 'L85a2 M320 Shotgun', 'kit': 'assault'},

    # Assault Rifle Underslung Shotguns
    'U_M416_M26_Buck': {'type': 'shotgun', 'name': 'M416 M26 Buckshot', 'kit': 'assault'},
    'U_M416_M26_Flechette': {'type': 'shotgun', 'name': 'M416 M26 Flechette', 'kit': 'assault'},
    'U_M416_M26_Frag': {'type': 'shotgun', 'name': 'M416 M26 Fragment', 'kit': 'assault'},
    'U_M416_M26_Slug': {'type': 'shotgun', 'name': 'M416 M26 Slug', 'kit': 'assault'},
    'U_SCAR-H_M26_Buck': {'type': 'shotgun', 'name': 'SCAR-H M26 Buckshot', 'kit': 'assault'},
    'U_SCAR-H_M26_Flechette': {'type': 'shotgun', 'name': 'SCAR-H M26 Flechette', 'kit': 'assault'},
    'U_SCAR-H_M26_Frag': {'type': 'shotgun', 'name': ' SCAR-H M26 Fragment', 'kit': 'assault'},
    'U_SCAR-H_M26_Slug': {'type': 'shotgun', 'name': ' SCAR-H M26 Slug', 'kit': 'assault'},
    'U_CZ805_M26_Buck': {'type': 'shotgun', 'name': ' CZ805 M26 Buckshot', 'kit': 'assault'},
    'U_CZ805_M26_Flechette': {'type': 'shotgun', 'name': ' CZ805 M26 Flechette', 'kit': 'assault'},
    'U_CZ805_M26_Frag': {'type': 'shotgun', 'name': ' CZ805 M26 Fragment', 'kit': 'assault'},
    'U_CZ805_M26_Slug': {'type': 'shotgun', 'name': ' CZ805 M26 Slug', 'kit': 'assault'},
    'U_M16A4_M26_Buck': {'type': 'shotgun', 'name': ' M16A4 M26 Buckshot', 'kit': 'assault'},
    'U_M16A4_M26_Flechette': {'type': 'shotgun', 'name': ' M16A4 M26 Flechette', 'kit': 'assault'},
    'U_M16A4_M26_Frag': {'type': 'shotgun', 'name': 'M16A4 M26 Fragment', 'kit': 'assault'},
    'U_M16A4_M26_Slug': {'type': 'shotgun', 'name': 'M16A4 M26 Slug', 'kit': 'assault'},

    # Gadgets
    'U_Defib': {'type': 'gadget', 'name': 'Defibrillator', 'kit': 'assault'},
    'U_PortableMedicpack': {'type': 'gadget', 'name': 'FIRST AID PACK', 'kit': 'assault'},
    'U_Medkit': {'type': 'gadget', 'name': 'MEDIC BAG', 'kit': 'assault'},
    'U_Repairtool': {'type': 'gadget', 'name': 'Repair-Tool', 'kit': 'engineer'},

    # Misc
    'Death': {'type': '', 'name': 'Death', 'kit': ''},
    'DamageArea': {'type': None, 'name': 'Suicide', 'kit': ''},
    'RoadKill': {'type': None, 'name': 'Road Kill', 'kit': ''},
    'SoldierCollision': {'type': None, 'name': 'Suicide (Collision)', 'kit': ''},
    'Suicide': {'type': None, 'name': 'Suicide', 'kit': ''},
}

BF4_WEAPON_GROUPS = {
    'shotgun': [k for k,v in BF4_WEAPON_NAMES_BY_ID.items() if v.get('type') == 'shotgun'],
    'handgun': [k for k,v in BF4_WEAPON_NAMES_BY_ID.items() if v.get('type') == 'handgun'],
    'explosive': [k for k,v in BF4_WEAPON_NAMES_BY_ID.items() if v.get('type') == 'explosive'],
}